Lw\Domain\Model\User\User:
  type: entity
  id:
    userId:
      column: id
      type: UserId
  table: lw_user
  repositoryClass: Lw\Infrastructure\Domain\Model\User\DoctrineUserRepository
  fields:
    email:
      type: string
    password:
      type: string
  manyToMany:
    wishes:
      cascade: ["persist"]
      targetEntity: Lw\Domain\Model\Wish\Wish
      joinTable:
        name: lw_user_wishes
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          wish_id:
            referencedColumnName: id
            unique: true