Lw\Domain\Model\Wish\Wish:
  type: entity
  table: lw_wish
  repositoryClass: Lw\Infrastructure\Persistence\Doctrine\Wish\DoctrineWishEmailRepository
  id:
    wishId:
      column: id
      type: WishId
      generator:
        strategy: NONE
  fields:
    address:
      type: string
    content:
      type: text
    userId:
      type: UserId
      column: user_id
