Lw\Domain\Model\User\User:
  type: entity
  table: user
  repositoryClass: Lw\Infrastructure\Persistence\Doctrine\User\DoctrineUserRepository
  id:
    surrogateUserId:
      column: id
      type: string
      generator:
        strategy: NONE
  fields:
    email:
      type: string
    password:
      type: string
