Lw\Infrastructure\Application\PublishedMessage:
  type: entity
  table: lw_event_published_message_tracker
  repositoryClass: Lw\Infrastructure\Application\DoctrinePublishedMessageRepository
  id:
    trackerId:
      column: tracker_id
      type: integer
      generator:
        strategy: AUTO
  fields:
    mostRecentPublishedMessageId:
      column: most_recent_published_message_id
      type: bigint
    typeName:
      type: string
      column: type_name
